name: demo-project
description: ''
version: 0.0.1
author: burak.yvz01@gmail.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: demoproject
  parentArtefactID: burakyvz01gmailcomteam
  buildSystem: wheel
  author: null
  createdAt: '2025-01-25 16:03:27'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: burak.yvz01@gmail.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-01-25 16:03:27'
    datasets:
      inputs:
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Account
      - gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=&tag=course_lab_sources/0.0.3&projectSubscriptionProjectId=13587&path=datasets/salesforce-Opportunity
      outputs:
      - datasets/enriched_accounts
    subgraphs: []
    dependencies: {}
datasets:
  datasets/enriched_accounts:
    name: enriched_accounts
    description: ''
    author: burak.yvz01@gmail.com
    createdAt: '2025-01-25 17:57:57'
    mode: batch
    physicalDatasets:
      workshop-fabric:
        fabricId: 20557
        datasetType: Database
        description: ''
        author: burak.yvz01@gmail.com
        createdAt: '2025-01-25 17:57:57'
templates: {}
jobs:
  jobs/daily_accounts:
    name: daily_accounts
    description: ''
    fabricUID: 20557
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: burak.yvz01@gmail.com
      onStart: true
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/enrich_accounts
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: true
    createdAt: '2025-01-25 18:02:36'
    author: burak.yvz01@gmail.com
    models: []
    sqlProjects: []
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-01-25 16:03:27'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-01-25T16:03:27.070946Z'
  name: plibMaven
  version: 8.7.1
  id: '338473765'
  createdAt: '2025-01-25T16:03:27.070946Z'
  type: plibMaven
- modifiedAt: '2025-01-25T16:03:27.070946Z'
  name: plibPypi
  version: 1.9.29
  id: '1778013435'
  createdAt: '2025-01-25T16:03:27.070946Z'
  type: plibPypi
projectDependencies:
  '13587':
    projectUID: 13587
    projectName: course_lab_sources
    repositoryPath: gitUri=http://gitserver:3000/wvwrv9bI_team_5938/wvwrv9bI_project_13587.git&subPath=
    version: course_lab_sources/0.0.3
    isDefault: false
    author: null
    createdAt: '2025-01-25 16:01:48'
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.39
    isDefault: true
    author: null
    createdAt: '2025-01-25 16:01:48'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2025-01-25 16:01:48'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
